//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPCOrderBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CPCOrderBooking()
        {
            this.CPCOrderBookingDetails = new HashSet<CPCOrderBookingDetail>();
        }
    
        public System.Guid Id { get; set; }
        public int OrderNo { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public byte Status { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.Guid> ApprovedById { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
    
        public virtual CPCEmployee CPCEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPCOrderBookingDetail> CPCOrderBookingDetails { get; set; }
    }
}
