//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMR.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppModuleSMTP
    {
        public long Id { get; set; }
        public Nullable<System.Guid> SmtpId { get; set; }
        public string ModuleId { get; set; }
    }
}
