//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMR.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserExtra
    {
        public System.Guid AppUserId { get; set; }
        public System.Guid ExtraId { get; set; }
        public string Value { get; set; }
    }
}
