//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMR.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmContactCompany
    {
        public System.Guid Id { get; set; }
        public System.Guid ContactId { get; set; }
        public byte Type { get; set; }
        public string Title { get; set; }
        public string Industry { get; set; }
        public string NoOfEmployees { get; set; }
        public Nullable<double> AnnualRevenue { get; set; }
        public string ResponsiblePerson { get; set; }
        public string Currency { get; set; }
        public string Fax { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string NINumber { get; set; }
        public Nullable<decimal> CompanyPercentage { get; set; }
    }
}
