//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMR.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmContact
    {
        public System.Guid Id { get; set; }
        public byte TargetedFor { get; set; }
        public byte Status { get; set; }
        public byte Source { get; set; }
        public string OtherSource { get; set; }
        public string Code { get; set; }
        public string Username { get; set; }
        public byte PrimaryEmailType { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public byte PrimaryPhoneType { get; set; }
        public string Phone { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public string SkypeID { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Description { get; set; }
        public Nullable<byte> Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public bool SubscribedForNewsletter { get; set; }
        public bool SubscribedForUpdates { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.Guid UpdatedByUserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedByUserId { get; set; }
        public Nullable<byte> TitlePrefix { get; set; }
        public Nullable<byte> TitleSuffix { get; set; }
        public Nullable<byte> ContactType { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
    }
}
