//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMR.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplate
    {
        public string Id { get; set; }
        public string Subject { get; set; }
        public string BodyContent { get; set; }
        public string DefaultContent { get; set; }
    }
}
