//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMR.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraFieldSection
    {
        public System.Guid Id { get; set; }
        public string Module { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string Section { get; set; }
        public string FieldType { get; set; }
        public string FieldName { get; set; }
        public string FieldValue { get; set; }
        public bool IsSystem { get; set; }
        public Nullable<int> SectionOrder { get; set; }
    }
}
